account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('dashboard/', views.DashBaoard.as_view(), name='dashboard'),
]

kodedautos/urls.py
from django.contrib import admin
from django.urls import path
from cars import views as car_view
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import include
from account import views as acc_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', car_view.CarsList.as_view(), name='home'),
    path('cars/<slug>/', car_view.CarDetail.as_view(), name='cardetail'),
    path('addcar/', car_view.CarCreate.as_view(), name='carcreate'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('cars/delete/<slug>/', car_view.DeleteCar.as_view(), name = 'deletecar'),
    path('cars/edit/<slug>/', car_view.UpdateCar.as_view(), name = 'updatecar')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

cars/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse
from django_resized import ResizedImageField

class Car(models.Model):
    AUTO = 'Automatic'
    MANUAL = 'Manual'
    PETROL = 'Petrol'
    DIESEL = 'Diesel'
    LEATHER = 'Leather'
    FABRIC = 'Fabric'
    NAIJA = 'Naija Used'
    FOREIGN = 'Foreign Used'
    TRANSMISSION = [
        (None, 'Choose'),
        (AUTO, 'Automatic'),
        (MANUAL, 'Manual'),
    ]
    FUEL = [
        (None, 'Choose'),
        (PETROL, 'Petrol'),
        (DIESEL, 'Diesel'),
    ]
    INTERIOR = [
        (None, 'Choose'),
        (LEATHER, 'Leather'),
        (FABRIC, 'Fabric'),
    ]
    USED = [
        (None, 'Choose'),
        (FOREIGN, 'Foreign Used'),
        (NAIJA, 'Naija Used'),
    ]
    by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='by')
    title = models.CharField(max_length=100)
    maker = models.CharField(max_length=20)
    model = models.CharField(max_length=20)
    price = models.PositiveIntegerField()
    mileage = models.PositiveIntegerField()
    foreign_or_naija_used = models.CharField(
        max_length=12,
        choices=USED
        )
    slugy = models.SlugField(unique=True, allow_unicode=True)
    uploaded = models.DateTimeField(default=timezone.now)
    colour = models.CharField(max_length=10)
    year = models.PositiveSmallIntegerField()
    doors = models.PositiveSmallIntegerField()
    transmission = models.CharField(
        max_length=10,
        choices=TRANSMISSION
        )
    fuel = models.CharField(
        max_length=10,
        choices=FUEL
        )
    interior = models.CharField(
        max_length=10,
        choices=INTERIOR
    )
    extra_features = models.TextField(max_length=500)
    description = models.TextField()
    # mainpic = models.ImageField(upload_to='images')
    mainpic = ResizedImageField(size=[600, 400], crop=['middle', 'center'], upload_to='images')
    pic1 = ResizedImageField(size=[600, 400], crop=['middle', 'center'], upload_to='images')
    pic2 = ResizedImageField(size=[600, 400], crop=['middle', 'center'], upload_to='images')
    pic3 = ResizedImageField(size=[600, 400], crop=['middle', 'center'], upload_to='images')
    pic4 = ResizedImageField(size=[600, 400], crop=['middle', 'center'], upload_to='images')
    pic5 = ResizedImageField(size=[600, 400], crop=['middle', 'center'], upload_to='images')

    def __str__(self):
        return f"{self.title} by {self.by.username}"

    def save(self, *args, **kwargs):
        self.slugy = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('cardetail', kwargs={'slug': self.slugy})

class Photos(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='car')
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.car.title

cars/forms.py
from django import forms
from .models import Car

class CarForm(forms.ModelForm):
    
    class Meta:
        model = Car
        exclude = ['by', 'uploaded', 'slugy']

class UploadPic(forms.ModelForm):

    class Meta:
        model = Car
        fields = ('mainpic', 'pic1', 'pic2', 'pic3', 'pic4', 'pic5')

account/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from cars.models import Car


class DashBaoard(TemplateView):
    template_name = 'account/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cars'] = Car.objects.order_by('-pk')
        return context

cars/views.py
from django.shortcuts import render
from django.views import generic
from .models import Car
from .forms import CarForm, UploadPic
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from django.core.mail import send_mail


@api_view(['POST'])
def send_email(request):
    rider = self.request.query_params.get('rider', None)
    balance = self.request.query_params.get('balance', None)
    pays_on = self.request.query_params.get('pays_on', None)
    date = self.request.query_params.get('date', None)
    
    
    



class CarsList(generic.ListView):
    # model = Car
    paginate_by = 10
    queryset = Car.objects.order_by('-pk')

class CarDetail(generic.DetailView):
    model = Car
    slug_field = 'slugy'

class CarCreate(LoginRequiredMixin, generic.CreateView):
    login_url = 'home'
    model = Car
    form_class = CarForm

    def form_valid(self, form):
        form.instance.by = self.request.user
        return super().form_valid(form)

class DeleteCar(LoginRequiredMixin, generic.DeleteView):
    model = Car
    slug_field = 'slugy'
    success_url = reverse_lazy('home')

class UpdateCar(LoginRequiredMixin, generic.UpdateView):
    model = Car
    slug_field = 'slugy'
    form_class = CarForm

cars/templates/cars/addphoto.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <div class="row">
        <div class="col"></div>
        <div class="col-md-8">
            <h4 align="center">Add photos of the car</h4>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" value="ADD PHOTOS" class="btn btn-primary btn-block">
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock body %}
    

cars/templates/cars/car_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block body %}
    <div class="row justify-content-center">
        <div class="col-10 col-md-8 col-lg-6 login" align="center">
            <form action="" method="post">
                {% csrf_token %}
                <div class="pic">
                    <img src="{{MEDIA_URL}}/{{object.mainpic}}" alt="" srcset="" class="carpic">
                </div>
                <h6 align="center" class="welcome">Are you sure you want to delete {{object.title}}?</h6>
                <a href="{% url 'cardetail' slug=object.slugy%}" class="btn btn-primary btn-lg">NO</a>
                <input type="submit" value="Yes, DELETE" class="btn btn-danger btn-lg" id="bt">
            </form>
        </div>
    </div>
{% endblock body %}
    

cars/templates/cars/car_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load cartag %}


{% block body %}
    <!-- <div class="pic">
        <img src="{{MEDIA_URL}}/{{object.mainpic}}" alt="" srcset="" class="carpic">
    </div> -->
    <div id="carouselExampleFade" class="carousel slide carousel-fade pic" data-ride="carousel" data-interval="false">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{{MEDIA_URL}}/{{object.mainpic}}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{{MEDIA_URL}}/{{object.pic1}}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{{MEDIA_URL}}/{{object.pic2}}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{{MEDIA_URL}}/{{object.pic3}}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{{MEDIA_URL}}/{{object.pic4}}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{{MEDIA_URL}}/{{object.pic5}}" class="d-block w-100" alt="...">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    <br>
    <div class="form-row">
        <div class="col pic">
            <img src="{{MEDIA_URL}}/{{object.pic1}}" alt="" srcset="" class="carpic">
        </div>
        <div class="col pic">
            <img src="{{MEDIA_URL}}/{{object.pic2}}" alt="" srcset="" class="carpic">
        </div>
        <div class="col pic">
            <img src="{{MEDIA_URL}}/{{object.pic3}}" alt="" srcset="" class="carpic">
        </div>
        <div class="col pic">
            <img src="{{MEDIA_URL}}/{{object.pic4}}" alt="" srcset="" class="carpic">
        </div>
        <div class="col pic">
            <img src="{{MEDIA_URL}}/{{object.pic5}}" alt="" srcset="" class="carpic">
        </div>
    </div>
    <h2 class="title">{{object.title}} {% if object.uploaded|timer < 24 %} <span class="badge badge-pill badge-warning">NEW</span> {% endif %}</h2>
    <span class="price">&#8358;{{object.price|intcomma}}</span>
                        <br>
    <h5>{{object.mileage|intcomma}} miles</h5>
    <h6>{{object.foreign_or_naija_used}}</h6>
    <h6>
        {% if object.uploaded|timer < 4 %}
            <span>Posted {{object.uploaded|naturaltime}}</span>
        {% else %}
            Posted {{object.uploaded|naturalday}}</span>
        {% endif %}
    </h6>
    <div class="row">
        <div class="col-6"><span class="option">Maker:</span> {{object.maker|title}}</div>
        <div class="col-4"><span class="option">Model: </span>{{object.model}}</div>
    </div>
    <div class="row">
        <div class="col-6"><span class="option">Year: </span>{{object.year}}</div>
        <div class="col-6"><span class="option">Transmission: </span>{{object.transmission}}</div>
    </div>
    <div class="row">
        <div class="col-6"><span class="option">Fuel: </span>{{object.fuel}}</div>
        <div class="col-4"><span class="option">Colour: </span>{{object.colour|title}}</div>
    </div>
    <br>
    <p class="features" align="center">
        {% for k in object.extra_features|splitter %}
        <span class="fea">
            <i class="fas fa-check-circle"></i></i>{{k|title}}
        </span>
        {% endfor %}
    </p>
    <br>
    <div class="note">
        <h5 class="welcome">Seller's note</h5>
        {{object.description}}
    </div>
    <br>
    {% if user.is_authenticated and user.is_superuser %}
    <div class="" align="center">
        <a href="{% url 'updatecar' slug=object.slugy %}">
            <button type="button" class="btn btn-outline-secondary btn-lg" id="bt">
                EDIT <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-tools" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M0 1l1-1 3.081 2.2a1 1 0 0 1 .419.815v.07a1 1 0 0 0 .293.708L10.5 9.5l.914-.305a1 1 0 0 1 1.023.242l3.356 3.356a1 1 0 0 1 0 1.414l-1.586 1.586a1 1 0 0 1-1.414 0l-3.356-3.356a1 1 0 0 1-.242-1.023L9.5 10.5 3.793 4.793a1 1 0 0 0-.707-.293h-.071a1 1 0 0 1-.814-.419L0 1zm11.354 9.646a.5.5 0 0 0-.708.708l3 3a.5.5 0 0 0 .708-.708l-3-3z"/>
                    <path fill-rule="evenodd" d="M15.898 2.223a3.003 3.003 0 0 1-3.679 3.674L5.878 12.15a3 3 0 1 1-2.027-2.027l6.252-6.341A3 3 0 0 1 13.778.1l-2.142 2.142L12 4l1.757.364 2.141-2.141zm-13.37 9.019L3.001 11l.471.242.529.026.287.445.445.287.026.529L5 13l-.242.471-.026.529-.445.287-.287.445-.529.026L3 15l-.471-.242L2 14.732l-.287-.445L1.268 14l-.026-.529L1 13l.242-.471.026-.529.445-.287.287-.445.529-.026z"/>
                  </svg>
            </button>
        </a>
        <a href="{% url 'deletecar' slug=object.slugy%}">
            <button type="button" class="btn btn-outline-danger btn-lg" id="bt">
                DELETE <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
                  </svg>
            </button>
        </a>
    </div>
    {% else %}
    <div class="" align="center">
        <a href="tel:08098184589">
            <button type="button" class="btn btn-outline-primary btn-lg" id="bt">
                Call Seller <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-telephone-outbound-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511zM11 .5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V1.707l-4.146 4.147a.5.5 0 0 1-.708-.708L14.293 1H11.5a.5.5 0 0 1-.5-.5z"/>
                    </svg>
            </button>
        </a>
        <a href="https://api.whatsapp.com/send?phone=2348098184589&text=http://127.0.0.1:8000{{MEDIA_URL}}{{object.mainpic}}%0AI%20saw%20this%20car%20on%20your%20website%20and%20would%20like%20to%20ask%20more%20about%20it.">
            <button type="button" class="btn btn-outline-success btn-lg" id="bt">
                WhatsApp <i class="fab fa-whatsapp"></i>
            </button>
        </a>
    </div>
    {% endif %}
{% endblock body %}
    

cars/templates/cars/car_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <div class="row">
        <div class="col"></div>
        <div class="col-md-8">
            <h4 align="center">Post a Car</h4>
            <form action="" method="post", enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" {%if object %}value="UPDATE CAR"{%else%}value="POST CAR"{%endif%} class="btn btn-primary btn-block">
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock body %}
    

cars/templates/cars/car_list.html
{% extends 'base.html' %}
{% load humanize %}
{% load cartag %}

{% block body %}
    {% if object_list %}
        <!-- <h2>{{object_list.count}} Car{{object_list.count|pluralize}} posted.</h2> -->
        <h3 class="welcome">You're welcome to Koded Automobiles</h3>
        {% for o in object_list %}
            <div class="car">
                <div class="row">
                    <!-- <a href="{% url 'cardetail' slug=o.slugy%}"> -->
                    <div class="col-md-4 pic">
                        <a href="{% url 'cardetail' slug=o.slugy%}">
                            <img src="{{MEDIA_URL}}/{{o.mainpic}}" alt="" srcset="" class="carpic">
                        </a>
                    </div>
                    <div class="col-md-8">
                        <h4>
                            <a href="{% url 'cardetail' slug=o.slugy%}">{{o.title}}</a> {% if o.uploaded|timer < 24 %} <span class="badge badge-pill badge-warning">NEW</span> {% endif %}
                        </h4>
                        <!-- <h5>Posted by: {{o.by}}</h5> -->
                        <span class="price">&#8358;{{o.price|intcomma}}</span>
                        <br>
                        <span>{{o.mileage|intcomma}} miles</span>
                        <div class="row">
                            <div class="col-6"><span class="option">Maker:</span> {{o.maker|title}}</div>
                            <div class="col-4"><span class="option">Model: </span>{{o.model}}</div>
                        </div>
                        <div class="row">
                            <div class="col-6"><span class="option">Year: </span>{{o.year}}</div>
                            <div class="col-6"><span class="option">Transmission: </span>{{o.transmission}}</div>
                        </div>
                        <div class="row">
                            <div class="col-6"><span class="option">Fuel: </span>{{o.fuel}}</div>
                            <div class="col-4"><span class="option">Colour: </span>{{o.colour|title}}</div>
                        </div>
                        <br>
                        <!-- <div class="row justify-content-end">
                            <div class="col-md-6">
                                {% if o.uploaded|timer < 4 %}
                                    <span>Posted {{o.uploaded|naturaltime}}</span>
                                {% else %}
                                    Posted {{o.uploaded|naturalday}}</span>
                                {% endif %}
                            </div>
                        </div> -->
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="row justify-content-center">
            <div class="pagination welcome col-10">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
            
                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
            
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    {% else %}
        <h2 align="center">No Cars have been added</h2>
        {% if user.is_authenticated and user.is_superuser %}
            <a href="#"><h3 align="center">Post a car</h3></a>
        {% endif %}
    {% endif %}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" integrity="sha384-v8BU367qNbs/aIZIxuivaU55N5GPF89WBerHoGA4QTcbUjYiLQtKdrfXnqAcXyTv" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/master.css" %}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static "images/kodedtran.png " %}"
                    alt="KodedAutos" srcset="" width="auto" height="60px"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}"><strong><span style="font-size: larger;">Home</span></strong></a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if  user.is_authenticated%}
                        {% if user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'carcreate' %}"><strong><span style="font-size: larger;">Post a Car</span></strong></a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:dashboard' %}"><strong><span style="font-size: larger;">DashBoard</span></strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}"><strong><span style="font-size: larger;">Log Out</span></strong></a>
                        </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}"><strong><span style="font-size: larger;">Log In</span></strong></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <br>
    <div class="container">
        {% block body %}

        {% endblock body %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
</body>
<footer>
    <!-- <div align="center" class="footerlogodiv"><img class="footerlogo" src="{% static "images/TYgreen.png" %}" alt="YANKEY TECHNOLOGIES" srcset="" width="45px" height="auto"></div> -->
    <div class="footercopyright"><h6 id="naijadgreen" align="center">KodedAutos © Copyright 2020. All rights reserved.</h6></div>
    <!-- <div align="center" class="socials"><a href="https://twitter.com/Naija_Paedia?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-size="large" data-show-count="false">Follow @Naija_Paedia</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script><i class="fab fa-instagram-square fa-3x"></i></div> -->
</footer>
</html>